name: ğŸ‘• Check linting of scss, js, ts, md files

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ğŸŸ¢ Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: ğŸ‘• Check scss files
        run: npm i stylelint-config-standard && npm run lint:scss
      - name: ğŸ‘• Check js, ts, md files
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write **/*.{js,ts,md}
          commit_message: âš¡ï¸ Prettified Code!
